### ISSUE TITLE
Multipage doesn't filter same pages

### ISSUE THREAD

**Issue by Seb147** [m42e/ttrss_plugin-feediron#12]
Here is the recipe I'm using : 

{
    "type": "xpath",
    "xpath": "div[@id='content-body']",
    "force_charset": "utf-8",
    "cleanup": [
        "header",
        "footer",
        "div[@class='smart-paging-pager']"
    ],
    "multipage": {
        "xpath": "li[@class='pager-item']\/a",
        "append": true
    }
}

And the url : http://www.atlantico.fr/decryptage/vitamines-naturels-bons-pour-sante-10-aliments-sains-qui-ne-sont-finalement-pas-jean-michel-cohen-2021310.html

When the plugin parse the content, it duplicates the content of the page 2 : 

LOG:
Fetching 3 links
Fetching 3 links
http://www.atlantico.fr/decryptage/vitamines-naturels-bons-pour-sante-10-aliments-sains-qui-ne-sont-finalement-pas-jean-michel-cohen-2021310.html
http://www.atlantico.fr/decryptage/vitamines-naturels-bons-pour-sante-10-aliments-sains-qui-ne-sont-finalement-pas-jean-michel-cohen-2021310.html/page/0/1
http://www.atlantico.fr/decryptage/vitamines-naturels-bons-pour-sante-10-aliments-sains-qui-ne-sont-finalement-pas-jean-michel-cohen-2021310.html/page/0/1

When I choose to grab the "Next" anchor and switch to recursive mode, it's working : 

    "multipage": {
        "xpath": "li[@class='pager-next']\/a",
        "append": true,
        "recursive": true
    }

**Comment by m42e** [comment]
Solved with e1ff82a
