### ISSUE TITLE
teltarif.de multi page

### ISSUE THREAD

**Issue by radlerandi** [m42e/ttrss_plugin-feediron#13]
Hallo,
wie muss ich es anstellen, dass Multi Pages von teltarif.de zu einem Artikel zusammengefasst werden? 
Die a-tags haben weder id oder class und mit der folgenden Variante funktioniert es auch nicht:
        "multipage": {
            "xpath": "a[text()='page']",
            "append": true,
            "recursive": true
        },
Bitte um einen Tipp.
(Eine andere Kontaktmöglichkeit hab ich nicht gefunden...)
Gruß
Andreas

**Comment by m42e** [comment]
hast du eine Beispiel URL?

**Comment by radlerandi** [comment]
mist, beim Anfang des Posts noch dran gedacht, dann aber vergessen. 
an der hatte ich mich versucht: 
http://www.teltarif.de/netzintegration-e-plus-o2-gsm-umts-lte/news/59016.html

**Comment by m42e** [comment]
Versuch es mal damit
```json
{
    "type": "xpath",
    "multipage": {
        "xpath": "a[contains(@href,'page')]",
        "append": true,
        "recursive": false
    },
    "xpath": "div[contains(@class,'art')]"
}
```

**Comment by radlerandi** [comment]
im Prinzip geht es, allerdings ist zumindest im Tester die zweite Seite jetzt 5x dran gehängt.

**Comment by m42e** [comment]
Hast du die aktuellste version?

**Comment by radlerandi** [comment]
bestimmt schon 2 monate alt, also wahrscheinlich nicht. muss ich mir zu hause dann mal ansehen.

**Comment by m42e** [comment]
Ja die duplikatfilterung ist neu

**Comment by radlerandi** [comment]
Plugin aktualisiert und jetzt funktioniert es. Danke für die Hilfe. :+1: 

Besteht Interesse an weiteren recipes? So ungefähr 7 umfangreichere könnte ich beisteuern. (nur wie?)

**Comment by m42e** [comment]
über die Export Funktion kannst du den JSON Code generieren, und den dann einfach in einer Datei speichern und in deinen Fork committen (Dateiname ist erst mal nicht relevant). Dann pushen und einen Pull request erstellen.

**Comment by radlerandi** [comment]
noch nie gemacht, und oh je, so viele Buttons.. aber ich glaub das erste recipe müsste vorliegen.

**Comment by m42e** [comment]
Du kannst mir einfach die Condor schicken

**Comment by m42e** [comment]
Hat doch geklappt werde es nachher mergen
