### ISSUE TITLE
Assistance with thestandard.com.hk

### ISSUE THREAD

**Issue by cwmke** [m42e/ttrss_plugin-feediron#18]
I've been trying for awhile to figure out a way to make this work but with no success.  I have a feeling split may work but I do not know regular expressions at all.  I'm wondering if you have any ideas.  

Essentially I want to combine all of the <p> elements since there aren't any xpath elements above them that I have been able to get to work.

I really appreciate any help if you can provide.  If not, thanks for the amazing plugin.

If you have the time, a sample link is below.  Thanks again.
http://www.thestandard.com.hk/news_detail.asp?pp_cat=31&art_id=155819&sid=44191877&con_type=1&d_str=20150402

**Comment by m42e** [comment]
Hi cwmke,

Thanks for using my plugin.
Try this config:

```
"thestandaard.com.uk":{
    "type": "xpath",
    "xpath": "table\/tr\/td\/b[contains(@class, 'bodyHeadline')]\/..\/..\/.."
}
```

Worked for me.
If you need further assistant please do not hesitate to contact me.

**Comment by cwmke** [comment]
I appreciate your response!  I'm wondering what you did means and how you were able to figure that out.  I think I figured out how you got the table/tr/td/b part, but when I attempt to apply the same thing to the below link (same site different xpath).

 I attempted to switch the 'b' with an 'i' to no avail.  It appears this one may be in an iframe.  Could that be the issue?  Thanks a lot for your patience.

**Comment by m42e** [comment]
You're welcome.
The XPath means, I'm looking for a table ```table``` containing a row ```tr``` with table data ```td``` containing a bold ```b``` element that has the class ```bodyHeadline```. If found, I step back to the table element by referencing the parent element ```..```.

Can you provide the link you are talking about, seems you have forgotten to add it to your comment. As soon as I get it I'll give it a try.

**Comment by cwmke** [comment]
Sorry about that.  Here you go.

http://www.thestandard.com.hk/breaking_news_detail.asp?id=59426

**Comment by m42e** [comment]
I think this is nealy what you can get:

```
{
    "type": "xpath",
    "xpath": [
        "table\/tr\/td\/b[contains(@class, 'bodyHeadline')]\/..\/..\/..",
        "table[contains(@class,'bodyCopy')]\/.."
    ],
    "cleanup": [
        "a[@name='anc_']",
        "table[contains(@class, 'breakingListTitle')]"
    ]
}
```

The content is structured completly different. And It contains unclosed tags, making it harder...

**Comment by cwmke** [comment]
This site has been giving me trouble for a few months.  I ended up switching some parts around from what you provided and below is my final version.  I just subscribed to your blog and look forward to using feediron for a long time.  Have a great day and thanks again for your help.

    },
    "thestandard.com.hk/breaking_news_detail": {
        "type": "xpath",
        "xpath": "table\/tr\/td\/b[contains(@class, 'bodyHeadline')]\/..\/..\/..",
        "cleanup": [
            "i",
            "b",
            "table"
        ]
    },
    "thestandard.com.hk": {
        "type": "xpath",
        "xpath": "table\/tr\/td\/span[contains(@class, 'bodyCopy')]\/..\/..\/..",
        "cleanup": [
            "a",
            "span[@class='bodyHeadline']",
            "i",
            "b",
            "table"
        ]
    }

**Comment by m42e** [comment]
You'r welcome!

Do you have experience in git? You can share the recipes for other users by creating a pull request.

**Comment by cwmke** [comment]
Only a little, but I'll look into it and add mine.  I have quite a few sites cleaned up.  The only problem I could see is that my formatting removes article titles, dates, and in some instances authors, since tt-rss adds the date and title already.
