### ISSUE TITLE
trouble with thehindu.com

### ISSUE THREAD

**Issue by cwmke** [m42e/ttrss_plugin-feediron#23]
I'm wondering if you can offer any help with this site.  I get leftovers from google ads at the bottom of every article and also occasionally get double city names at the top.  Below is my config and a link.  Thanks a lot.

http://www.thehindu.com/news/international/four-school-girls-jump-into-nepals-mahakali-river-after-poor-results/article7098985.ece

http://www.thehindu.com/news/international/netajis-grand-nephew-meets-modi-in-berlin/article7101062.ece

    "type": "xpath",
    "xpath": [
        "span[@class='upper']",
        "[p\/img[@class='main-image']\/..",
        "div[@class='article-text']"
    ],
    "join_element": "<p>",
    "cleanup": [
        "script",
        "div[@class='related-column']",
        "div[@id='articleKeywords']",
        "div[@class='noline']",
        "span",
        "div[@id='keywordline']",
        "div[@class='rel-block-sec']",
        "div[@class='line1A']",
        "div[@id='addshare']",
        "div[@class='line2']",
        "div[@class='logocode']",
        "div[@class='OUTBRAIN']",
        "div[@class='artBanTopLine']",
        "div[@class='banner-ad']",
        "div[@class='rel-block-news']",
        "div[@id='ad1']",
        "noscript",
        "script",
        "br",
        "a",
        "object"
    ],
    "modify": [
        {
            "type": "replace",
            "search": [
                "else if (google_ads",
                "google_ads",
                "Adjust text sizes to occupy the majority of ad space"
            ],
            "replace": [
                "",
                "",
                ""
            ]
        }
    ]

**Comment by m42e** [comment]
Looks like the xml parser is getting weired parsing all the JavaScript things within the code...

You can try the branch allitems with the following config:

```
{
    "type": "xpath",
    "xpath": [
        "span[@class='upper']",
        "[p\/img[@class='main-image']\/..",
        {
            "xpath": "div[@class='article-text']\/p",
            "index": "all"
        }
    ],
    "join_element": "<br>",
    "cleanup": [
        "script"
    ],
    "modify": [
        {
            "type": "replace",
            "search": [
                "else if (google_ads",
                "google_ads",
                "Adjust text sizes to occupy the majority of ad space"
            ],
            "replace": [
                "",
                "",
                ""
            ]
        }
    ]
}
```

**Comment by cwmke** [comment]
I wasn't able to get it to work.  I tried split too but I'm not sure exactly how to properly use that.  I tried to follow the recipe in Der Postillon, but no luck.  Thanks for your response and continued help.

{
    "type": "split",
    "xpath": "div[@class='article-body']",
    "steps": [
        {
            "after": "\/@class='articleLead'>\/",
            "before": "\/<divclass='noline'><\/"
        }
    ]
}

**Comment by m42e** [comment]
Try this
```
{
    "type": "split",
    "xpath": "div[@class='article-body']",
    "steps": [
        {
            "after": "#class=\"articleLead\".#",
            "before": "#<script#"
        }
    ]
}
```

**Comment by cwmke** [comment]
Perfect!  Thank you very much.  It's good to resolve that one.  It's been bothering me for awhile.  I'll get the updates added to a pull request tomorrow.

**Comment by cwmke** [comment]
Is there a way to still use multiple xpaths?  Such as...(which doesn't work)

    "type": "split",
    "xpath": [
        "[p\/img[@class='main-image']\/..",
        "div[@class='article-body']"
    ],
    "steps": [
        {
            "after": "#class=\"articleLead\".#",
            "before": "#<script#"
        }
    ]

**Comment by m42e** [comment]
the Xpath(s) are completly ignored if type is set to ```split```

**Comment by cwmke** [comment]
I'm giving 'index' another shot but I don't seem to be able to get 'all' to work.  Is there something I'm doing incorrectly?  It works fine if I replace 'all' with a number.

    "type": "xpath",
    "xpath": [
        "div\/img[@class='main-image']",
        "div[@class='articleLead']",
        {
            "xpath": "p",
            "index": "all"
        },
        "span[@class='upper']"
    ],
    "join_element": "<br>"

**Comment by m42e** [comment]
Did you checkout the allitems branch?

**Comment by cwmke** [comment]
My mistake.  That did the trick.  Thanks a lot.  That fixed everything.
