### ISSUE TITLE
Postillon seems to be not working

### ISSUE THREAD

**Issue by trockenasche** [m42e/ttrss_plugin-feediron#30]
the recipe `postillon_de` doesn't work, I change the url and made a test, the config is triggered but doesn't get a full feed. Any suggestions?

**Comment by GoodSoulGermany** [comment]
"der-postillon.com": {
        "type": "xpath",
        "xpath": "div[contains(@class,'entry-content')]",
        "force_unicode": true
    }

**Comment by trockenasche** [comment]
Thanks, that's works!
