### ISSUE TITLE
Is old feedmod settings compatible with feediron?

### ISSUE THREAD

**Issue by Narga** [m42e/ttrss_plugin-feediron#32]
I had a ton of feedmod settings with 50 feeds, I want to moving to feediron but I'm not sure feediron can read and fully compatible with them.
Can you confirm this issue?

**Comment by GoodSoulGermany** [comment]
100% compatible

2015-06-10 11:34 GMT+02:00 Nguyễn Đình Quân <notifications@github.com>:

**Comment by Narga** [comment]
:+1:

**Comment by Narga** [comment]
OMG it works like charm, I wish I could switched it before. Thanks for aweasome plugin.

**Comment by GoodSoulGermany** [comment]
Enjoy ;)
