### ISSUE TITLE
Is Feediron possible to refresh old items?

### ISSUE THREAD

**Issue by Narga** [m42e/ttrss_plugin-feediron#34]
I want reformat old items in feed after change the configuration.

**Comment by m42e** [comment]
That is not possible due to limitations of tt-rss. I have done this before but the field that stores the state is now handled by tt-rss.

Besides that, you can remove the flag from the database if you have direct access.

**Comment by Narga** [comment]
Great! Can you tell me more detail about the flag that I can remove it to refresh the old items. I'm hosting TTRSS on my own server and I can manage database.

**Comment by m42e** [comment]
In the table ttrss_entries remove the ```feediron``` from the plugin_data field. Hopefully all the articles will be processed.

**Comment by Narga** [comment]
Thanks, my 'ttrss_entries' has 180k row, so I only remove 'feediron' for specified feeds.

**Comment by Narga** [comment]
Then I wait for 2 times cycle updated but it's not effected. I still get the old feed content.

**Comment by m42e** [comment]
Afair It reprocesses the articles when you open them. At least it behaved this way some time ago. Maybe the mechnism within tt-rss has changed.

**Comment by Narga** [comment]
I guessed tt-rss has changed. I've tried refresh the feed, read then refresh, read and set unread then refresh but it's not change. But when I remove the re-add the feed, it's work as it (the older item has lost)

**Comment by m42e** [comment]
I think this is not a behaviour I'd be able to change within feediron

**Comment by Narga** [comment]
I've found the way to refresh old or incorrect fetched content, here are some steps to refresh items with feediron
* Archiving selected items.
* Go to Archives section then delete selected items which you want to refresh.
* Back to the feed and refresh it to fetch new content.
:smile_cat:

**Comment by shawn8888** [comment]
> 

it works!
