### ISSUE TITLE
heise recipes don't work

### ISSUE THREAD

**Issue by kuestenjunge** [m42e/ttrss_plugin-feediron#41]
Tried to use the heise config files with telepolis, developer and newsticker.
Nothing works, the url of given feeds and articles doesn't match

**Comment by m42e** [comment]
@phbaer Seems something may be wrong with your shared recipes :)

**Comment by phbaer** [comment]
Ha, seems to be a typical case of "works on my system" :-)

Could you please add more details, steps/URLs/...?

Well possible that there are issues. Will try to fix them.

**Comment by kuestenjunge** [comment]
Sure, this is my feediron configuration:

{
    	"name": "heise.de Developer",
    	"url": "http://www.heise.de/developer/",
    	"match": "heise.de\/developer",
    	"author": "phbaer",
    	"config": {
        		"type": "xpath",
        		"xpath": "article",
        		"cleanup": [
            			"p[contains(@class,'news_datum')]",
            			"div[contains(@class,'readspeakerr')]",
            			"h1[contains(@class,'clear')]",
            			"noscript",
            			"comment()",
            			"script",
            			"footer"		
        ]	
    }
}

Here is the feed URL:
http://www.heise.de/developer/rss/news-atom.xml

**Comment by phbaer** [comment]
Just tested it locally. The recipes generate names like "heise.de.developer" which might be not what we want... I have committed fixes for the recipes and created a pull request.

Hope that fixes the issue.

**Comment by m42e** [comment]
merged pull request, closing this ticket as resolved.
