### ISSUE TITLE
Error with new tt-rss

### ISSUE THREAD

**Issue by horosgrisa** [m42e/ttrss_plugin-feediron#46]
After upgrading to new tt-rss, I obtain following error
```
Warning:  array_key_exists() expects parameter 2 to be array, null given in /var/www/tt-rss/plugins.local/feediron/init.php on line 195
```
Mysql schema_version = 130

**Comment by dugite-code** [comment]
Same as issue #33.  I did do some test code adding an array check but never opened a pull request as it doesn't signify anything is broken. 

This should only show in your logs if you don't have `"debug": false` set on youre configuration
