### ISSUE TITLE
Missing items in some feeds

### ISSUE THREAD

**Issue by Arrrchie** [m42e/ttrss_plugin-feediron#6]
For instance Cyanide and happiness
 http://pipes.yahoo.com/pipes/pipe.run?_id=9b91d1900e14d1caff163aa6fa1b24bd&_render=rss

My Recipe for this is:

    "explosm.net": {
        "type": "xpath",
        "xpath": "img[@id='main-comic']",
        "force_charset": "utf-8"
    }

This works nicely until commit 7728e91. After that the article is empty.

**Comment by m42e** [comment]
I wonder this worked ever before. Because feediron used getInnerHtml since the beginning.

But this should work for you:

```
"explosm.net": {
    "type": "xpath",
    "xpath": "img[@id='main-comic']/..",
    "force_charset": "utf-8"
}
```

**Comment by Arrrchie** [comment]
This works for me. Thanks!
