### ISSUE TITLE
Feediron stop working on Tiny Tiny RSS v17.1 (ecab435) 

### ISSUE THREAD

**Issue by Narga** [m42e/ttrss_plugin-feediron#65]
Today, I've reset the TTRSS preferences for fresh and re-configs. But after enable feediron, it's disappeared from the Preferences Tabs

**Comment by m42e** [comment]
Hmm, I'm very sorry I hadn't updated a long time ago and I'm currently not able to maintain it. I'm sorry.

**Comment by Narga** [comment]
Thanks for your reply, I will fixing by myself, thank again for great job, I'm still using Tiny Tiny RSS until now because you plugin 😄

**Comment by shoeper** [comment]
If you fix it please share your results.

**Comment by Narga** [comment]
OK, I'll trying to rewrite it from scratch but if I have time :D 
I've rolled back my database and lost for 10 days but it's worth to bring feedion back temporaty.

**Comment by Narga** [comment]
@shoeper @m42e I've cloned ttrss and replace my old ttrss source with fresh new. With just only feediron plugins, it's activable again and the Feediron tab appeared.
It's fixed temporary.
