### ISSUE TITLE
Multipage handling without links on the first page

### ISSUE THREAD

**Issue by Seb147** [m42e/ttrss_plugin-feediron#9]
Take this page for example : http://www.dorkly.com/post/71930/7-terrible-parts-that-almost-ruined-great-games

There is a link "Next >", but there is no direct link to page 3 & 4 from the first page of the article.

We could imagine make the process in a recursive way, to be able to grab all the pages ?

**Comment by m42e** [comment]
Sounds like a nice feature. well let me think about it.

**Comment by m42e** [comment]
Have a look at the recursive branch. I haven't tried it yet.

**Comment by m42e** [comment]
Seems to work :+1: 

```
{
    "type": "xpath",
    "multipage": {
        "xpath": "a[contains(@data-ga-category,'Pagination') and text() = 'Next']",
        "recursive": true,
        "append": true
    },
    "xpath": "div[contains(@class,'post-content')]"
}
```

**Comment by m42e** [comment]
Well, as I said before it works, but there is potential to optimize. Maybe something like caching the already fetched urls improves speed a lot.

**Comment by m42e** [comment]
fa539a4 should do the trick.

**Comment by Seb147** [comment]
Thanks for the feature :)

However, there seem to have a problem :

Writing into cache
LOG:
Fetching 7 links
Fetching 7 links
http://www.dorkly.com/post/71930/7-terrible-parts-that-almost-ruined-great-games
http://www.dorkly.com/post/71930/7-terrible-parts-that-almost-ruined-great-games/page:2
http://www.dorkly.com/post/71930/7-terrible-parts-that-almost-ruined-great-games/page:2
http://www.dorkly.com/post/71930/7-terrible-parts-that-almost-ruined-great-games/page:3
http://www.dorkly.com/post/71930/7-terrible-parts-that-almost-ruined-great-games/page:3
http://www.dorkly.com/post/71930/7-terrible-parts-that-almost-ruined-great-games/page:4
http://www.dorkly.com/post/71930/7-terrible-parts-that-almost-ruined-great-games/page:4

As a result, the content of the pages 2 to 4 are duplicated.

**Comment by m42e** [comment]
hmmm, it worked for me I thought.....

**Comment by m42e** [comment]
Ok, you're right. I'll check this.

**Comment by Seb147** [comment]
wow, I didn't saw you made another commit. That seems to work perfectly, thanks! :)

**Comment by m42e** [comment]
Ok so it works for you and me. I'll merge #10 into master.
